import type { PersonInfo, SubmitKycRequest } from "@/types/onboarding";

export function createEmptyPerson(): PersonInfo {
  return {
    gender: "Male",
    idCard: "",
    nameEN: "",
    country: "",
    nameCHS: "",
    surname: "",
    authType: "",
    birthday: "",
    surnameCHS: "",
    certificateTerm: ["", ""],
    residenceAddress: "",
    residenceCountry: "",
    shareholdingRatio: "",
    verificationType: "idHolding",
    idHolding: [],
  };
}

export function createDefaultKycForm(): SubmitKycRequest {
  return {
    enterpriseInfo: {
      incorporationCertificate: [],
      incorporationCertificateNo: "",
      establishTime: "",
      enterpriseEN: "",
      enterpriseNameCHS: "",
      registerRegion: "",
      registerAddress: "",
      businessRegistration: [],
      businessRegistrationNo: "",
      phone: "",
      isChangeEnterpriseNameInFiveYears: "No",
      usedEnterpriseName: "",
      enterpriseType: "Private limited company",
      enterpriseDomain: "",
      businessRegion: [],
      mainBusinessAddress: "",
      industry: "",
      subIndustry: "",
      initialFundingSource: "Business income",
      wealthSource: "",
      continuousFundingSource: "",
      salesVolumeLastyear: "",
      employeeNum: "<10",
      openAccountPurpose: "Business operation",
      incumbency: [],
      associationRules: [],
      authenticMaterials: [],
      managerCountry: "",
      managerAuthType: "",
      managerVerificationType: "idHolding",
      managerIdHolding: [],
      managerCertificateTerm: ["", ""],
      managerSurnameCHS: "",
      managerNameCHS: "",
      managerSurname: "",
      managerNameEN: "",
      managerBirthday: "",
      managerGender: "Male",
      managerIdCard: "",
      managerResidenceCountry: "",
      managerResidenceAddress: "",
      managerContactsEmail: "",
      authorizationLetter: [],
      equityStructure: [],
      middleTierShareholders: "No",
      nnc1: [],
    },
    shareholdersInfo: [createEmptyPerson()],
    directorInfo: [createEmptyPerson()],
  };
}
