import type { KycFormValues } from "@/lib/validations/onboarding";
import { createEmptyPerson } from "./defaults";

export function createKycFormDefaults(): KycFormValues {
  const person = () => ({
    ...createEmptyPerson(),
    nameCHS: "",
    surnameCHS: "",
    certificateStart: "",
    certificateEnd: "",
    idHoldingPaths: [""],
  });

  return {
    enterpriseInfo: {
      incorporationCertificatePaths: [""],
      incorporationCertificateNo: "",
      establishTime: "",
      enterpriseEN: "",
      enterpriseNameCHS: "",
      registerRegion: "",
      registerAddress: "",
      businessRegistrationPaths: [""],
      businessRegistrationNo: "",
      phone: "",
      mainBusinessAddress: "",
      isChangeEnterpriseNameInFiveYears: "No",
      usedEnterpriseName: "",
      enterpriseType: "Private limited company",
      enterpriseDomain: "",
      businessRegion: "",
      industry: "",
      subIndustry: "",
      initialFundingSource: "Business income",
      wealthSource: "Business income",
      continuousFundingSource: "Business income",
      salesVolumeLastyear: "HKD 0-2,500,000",
      employeeNum: "<10",
      openAccountPurpose: "Business operation",
      incumbencyPaths: [],
      associationRulesPaths: [""],
      authenticMaterialsPaths: [""],
      managerCountry: "",
      managerAuthType: "",
      managerIdHoldingPaths: ["", "", ""],
      managerCertificateStart: "",
      managerCertificateEnd: "",
      managerSurnameCHS: "",
      managerNameCHS: "",
      managerSurname: "",
      managerNameEN: "",
      managerBirthday: "",
      managerGender: "Male",
      managerIdCard: "",
      managerResidenceCountry: "",
      managerResidenceAddress: "",
      managerContactsEmail: "",
      authorizationLetterPaths: [],
      equityStructurePaths: [],
      middleTierShareholders: "No",
      nnc1Paths: [],
    },
    shareholdersInfo: [{ ...person(), shareholdingRatio: "" }],
    directorInfo: [person()],
  };
}
